version: "3.8"
services:
  mi-bd:
    image: mysql:5.7
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT # puerto de mi computadora : puerto interno del contenedor
  app:
    build: .
    env_file: ./.env
    depends_on:
      - mi-bd
    links:
      - mi-bd
    ports:
      - $APP_LOCAL_PORT:$APP_DOCKER_PORT